# Generated by Django 3.2.8 on 2021-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211016_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(null=True, related_name='choice', to='main.Choice', verbose_name='выбор(-ы)'),
        ),
    ]
